### ISSUE TITLE
Starting up the docker-build.yml file with no internal.db file fails

### ISSUE THREAD

**Issue by dougthor42** [dougthor42/trendlines#110]
Starting up the docker-build.yml file with no internal.db file fails

## Steps to Reproduce
1. Delete any `internal.db` file that you may have.
2. Run `docker-compose -f docker-build.yml build`
3. Run `docker-compose -f docker-build.yml up`
4. navigate to http://localhost:5000
5. See error logs.
6. Check the current working dir, see a `trendlines.db` directory.

## Expected Result
A `trendlines.db` **file** should be created.

## Actual Result
A `trendlines.db` **directory** is created.

## Notes
This does not happen when running with the script `runserver.py`. With this, a **file** is correctly created.

## Error
```
trendlines_1  | [Wed Feb 27 23:41:34.892956 2019] [wsgi:error] [pid 15:tid 140411542562560] 2019-02-27 23:41:34.892 | INFO     | trendlines._logging:_setup_console_logging:57 - Console logging initialized.
trendlines_1  | [Wed Feb 27 23:41:34.893194 2019] [wsgi:error] [pid 15:tid 140411542562560] 2019-02-27 23:41:34.893 | DEBUG    | trendlines.app_factory:create_app:23 - Creating app.
trendlines_1  | [Wed Feb 27 23:41:34.893872 2019] [wsgi:error] [pid 15:tid 140411542562560] 2019-02-27 23:41:34.893 | INFO     | trendlines.app_factory:create_app:29 - Loaded config file '/data/trendlines.cfg'
trendlines_1  | [Wed Feb 27 23:41:34.894105 2019] [wsgi:error] [pid 15:tid 140411542562560] 2019-02-27 23:41:34.893 | DEBUG    | trendlines.app_factory:create_app:42 - Registering blueprints.
trendlines_1  | [Wed Feb 27 23:41:34.895210 2019] [wsgi:error] [pid 15:tid 140411542562560] 2019-02-27 23:41:34.895 | DEBUG    | trendlines.app_factory:create_db:95 - Creating database: '/data/internal.db'.
trendlines_1  | [Wed Feb 27 23:41:34.895693 2019] [wsgi:error] [pid 15:tid 140411542562560] 2019-02-27 23:41:34.895 | ERROR    | trendlines.app_factory:create_db:108 - Unable to open database file '/data/internal.db'
trendlines_1  | [Wed Feb 27 23:41:34.895754 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862] mod_wsgi (pid=15): Failed to exec Python script file '/var/www/wsgi.py'.
trendlines_1  | [Wed Feb 27 23:41:34.895788 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862] mod_wsgi (pid=15): Exception occurred processing WSGI script '/var/www/wsgi.py'.
trendlines_1  | [Wed Feb 27 23:41:34.896031 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862] Traceback (most recent call last):
trendlines_1  | [Wed Feb 27 23:41:34.896096 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2658, in connect
trendlines_1  | [Wed Feb 27 23:41:34.896103 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     self._state.set_connection(self._connect())
trendlines_1  | [Wed Feb 27 23:41:34.896111 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2935, in _connect
trendlines_1  | [Wed Feb 27 23:41:34.896115 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     **self.connect_params)
trendlines_1  | [Wed Feb 27 23:41:34.896132 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862] sqlite3.OperationalError: unable to open database file
trendlines_1  | [Wed Feb 27 23:41:34.896142 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]
trendlines_1  | [Wed Feb 27 23:41:34.896145 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862] During handling of the above exception, another exception occurred:
trendlines_1  | [Wed Feb 27 23:41:34.896148 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]
trendlines_1  | [Wed Feb 27 23:41:34.896155 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862] Traceback (most recent call last):
trendlines_1  | [Wed Feb 27 23:41:34.896521 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/var/www/wsgi.py", line 9, in <module>
trendlines_1  | [Wed Feb 27 23:41:34.896560 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     application = create_app()
trendlines_1  | [Wed Feb 27 23:41:34.896575 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/trendlines/src/trendlines/app_factory.py", line 47, in create_app
trendlines_1  | [Wed Feb 27 23:41:34.896579 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     create_db(app.config['DATABASE'])
trendlines_1  | [Wed Feb 27 23:41:34.896585 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/trendlines/src/trendlines/app_factory.py", line 99, in create_db
trendlines_1  | [Wed Feb 27 23:41:34.896589 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     orm.db.connect()
trendlines_1  | [Wed Feb 27 23:41:34.896595 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2659, in connect
trendlines_1  | [Wed Feb 27 23:41:34.896599 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     self._initialize_connection(self._state.conn)
trendlines_1  | [Wed Feb 27 23:41:34.896605 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2509, in __exit__
trendlines_1  | [Wed Feb 27 23:41:34.896608 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     reraise(new_type, new_type(*exc_args), traceback)
trendlines_1  | [Wed Feb 27 23:41:34.896615 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/usr/local/lib/python3.7/site-packages/peewee.py", line 186, in reraise
trendlines_1  | [Wed Feb 27 23:41:34.896618 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     raise value.with_traceback(tb)
trendlines_1  | [Wed Feb 27 23:41:34.896624 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2658, in connect
trendlines_1  | [Wed Feb 27 23:41:34.896628 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     self._state.set_connection(self._connect())
trendlines_1  | [Wed Feb 27 23:41:34.896636 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]   File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2935, in _connect
trendlines_1  | [Wed Feb 27 23:41:34.896673 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862]     **self.connect_params)
trendlines_1  | [Wed Feb 27 23:41:34.896698 2019] [wsgi:error] [pid 15:tid 140411542562560] [remote 172.20.0.1:51862] peewee.OperationalError: unable to open database file
```

**Comment by dougthor42** [comment]
On the dev server (using a standard `docker-compose.yml` file) a new database file was correctly made.

Here's the docker-compose.yml file that was used:

```yaml
version: "3.2"
services:
  trendlines:
    image: dougthor42/trendlines:latest
    restart: always
    ports:
      - "127.0.0.1:5082:80"
    volumes:
      - type: bind
        source: /var/www/trendlines
        target: /data
    networks:
      - frontend

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  celery:
    image: dougthor42/trendlines:latest
    restart: always
    ports:
      - "2003:9999"
    volumes:
      - type: bind
        source: /var/www/trendlines
        target: /data
    command: celery worker -l info -A trendlines.celery_app.celery
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
```
